from hakim_legal_schema.bundle import BundleRelation, DocumentBundle, FieldConflict
from hakim_legal_schema.document import (
    ExtractedField,
    QualityReport,
    QualityStatus,
    StructuredDocument,
    StructuredWarning,
    VisualEvidence,
)
from hakim_legal_schema.entities import (
    Article,
    ArticleVersion,
    Case,
    Court,
    CourtDecision,
    DeadlineRule,
    DocumentVersion,
    Institution,
    Law,
    LegalConcept,
    LegalDocument,
    Paragraph,
    Procedure,
    Publication,
    Remedy,
    Source,
    UserDocument,
)
from hakim_legal_schema.enums import (
    AuthorityLevel,
    DocumentType,
    IngestionStatus,
    MevzuatTur,
    ProvenanceKind,
    RelationType,
)
from hakim_legal_schema.evidence import evidence_from_fields
from hakim_legal_schema.ids import (
    CanonicalIdError,
    article_id,
    article_version_id,
    court_id,
    decision_id,
    law_id,
    parse_canonical_id,
)
from hakim_legal_schema.ingestion import IngestionReport
from hakim_legal_schema.relations import LegalRelation
from hakim_legal_schema.temporal import resolve_version

SCHEMA_VERSION = "1.0.0"

__all__ = [
    "SCHEMA_VERSION",
    "Article",
    "ArticleVersion",
    "AuthorityLevel",
    "BundleRelation",
    "CanonicalIdError",
    "Case",
    "Court",
    "CourtDecision",
    "DeadlineRule",
    "DocumentBundle",
    "DocumentType",
    "DocumentVersion",
    "ExtractedField",
    "FieldConflict",
    "IngestionReport",
    "IngestionStatus",
    "Institution",
    "Law",
    "LegalConcept",
    "LegalDocument",
    "LegalRelation",
    "MevzuatTur",
    "Paragraph",
    "Procedure",
    "ProvenanceKind",
    "Publication",
    "QualityReport",
    "QualityStatus",
    "RelationType",
    "Remedy",
    "Source",
    "StructuredDocument",
    "StructuredWarning",
    "UserDocument",
    "VisualEvidence",
    "article_id",
    "article_version_id",
    "court_id",
    "decision_id",
    "evidence_from_fields",
    "law_id",
    "parse_canonical_id",
    "resolve_version",
]
